apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: azure-blob-scaledobject
  namespace: keda-scale
spec:
  maxReplicaCount: 4
  pollingInterval: 10 # Optional. Default: 30 seconds
  cooldownPeriod: 5 # Optional. Default: 300 seconds
  scaleTargetRef:
    deploymentName: scale-nginx
  triggers:
    - type: azure-blob
      metadata:
        accountName: kedaexample # Optional. Name of Azure Storage Account
        blobContainerName: kedaexample # Required: Name of Azure Blob Storage container
        connection: connectionString # Optional. Name of secret key
        blobCount: "2" # Optional. Amount of blobs to scale out on. Default: 5 blobs
        blobPrefix: "" # Optional. Prefix for the Blob. Use this to specifiy sub path for the blobs if required. Default : ""
